### ISSUE TITLE
Don't have push access

### ISSUE THREAD

**Issue by ajdubovoy** [lewagon/grocery-bud-boilerplate#1]
@Eschults I'd like to change the stimulus import here to match https://github.com/lewagon/stimulus-js-boilerplate/commit/e6889afb3ab96c1b23f060f7995dcb7a8824ba30, but i don't have push access to this repo. Would you be able to please add me? Thanks you!

**Comment by Eschults** [comment]
✅ Done

<img width="1532" alt="Screenshot 2024-11-07 at 15 06 30" src="https://github.com/user-attachments/assets/aa0ada11-025b-433e-95e8-aa55d1978b70">

**Comment by ajdubovoy** [comment]
Thanks!
